name: Call central docker build

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'docker/**'
      - 'requirements.txt'
      - 'pyproject.toml'

jobs:
  build:
    uses: z0nd4/actions-templates/.github/workflows/build-push-latest.yml@v1
    with:
      repo_full_name: ${{ github.repository }}
    secrets: inherit
